# Generated by Django 4.1.7 on 2023-03-01 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'XS(0-3.5 kg)'), ('S', 'S(3.5-7 kg)'), ('M', 'M(7-12 kg)'), ('L', 'L(12-16 kg)'), ('XL', 'XL(16-20 kg)'), ('XXL', 'XXL(20-30 kg)'), ('OTHER', 'OTHER(30+ kg)')], max_length=13)),
                ('animal', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=3)),
                ('category', models.CharField(choices=[('toys', 'toys'), ('Food and related products', 'Food and related products'), ('sleep ', 'sleep '), ('clothing', 'clothing'), ('Straps ', 'Straps '), ('cages', 'cages')], max_length=25)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('age', models.FloatField()),
                ('place', models.CharField(max_length=200)),
                ('prefix', models.CharField(choices=[('050', '050'), ('052', '052'), ('053', '053'), ('054', '054'), ('057', '057'), ('058', '058')], max_length=3)),
                ('phone', models.CharField(max_length=7)),
                ('items', models.ManyToManyField(to='myapp.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
